dictionary = {
    "Greeting": ["Hello", "Good morning", "Good afternoon", "How are you?", "Hello, how are you all?", 
                 "Good morning, can you help me?", "Good afternoon, I need information.", 
                 "Hello, is anyone available?", "Greetings!", "How's it going?", "How's everything!", 
                 "Hello, I hope you're all well!", "Good morning! How's everything?", "Good afternoon! How can I help you?", 
                 "Hello, how's everything going over there?"],
    "Complaint": ["I would like to make a complaint", "I'm not satisfied with the service", "The product arrived damaged", 
                  "I didn't like the attention received", "The service was very slow", "The product quality is not good",
                  "I'm dissatisfied with what I received", "The shipping was delayed", "I'm not happy with the purchase", 
                  "The product didn't meet my expectations", "The service wasn't as expected", "I feel disappointed with the purchase"],
    "Claim": ["I need to make a claim for an error", "I want to make a claim", "This is unacceptable, I want a solution",
              "I'm very upset, I need to make a claim.", "I want to report an error with my order.",
              "This doesn't fulfill what was promised, I want a solution.", "The product doesn't work, how do I make a claim?",
              "I want my money back, the product arrived in bad condition.", "This is a serious error, I need help.",
              "They haven't responded on time, I want to make a claim", "This problem is urgent, I need you to solve it now", 
              "My product doesn't work, I want to know what to do"],
    "Request": ["I would like to request information", "I need to know more details about the product", "Please, send me more information", 
                "Can you give me more details?", "I would like to know more about your services", "Please, send me a quote", 
                "I would like to know the product features", "Could you send me more information by email?", 
                "I'm interested in knowing more", "Do you have any product catalog?", "Can you give me additional details?", 
                "How can I get more information about what you offer?"],
    "Farewell": ["Goodbye", "See you later", "See you", "Bye", "See you soon", "Thank you", "Take care", "Until next time", 
                 "Have a good day", "See you soon", "Until then", "Thanks for everything", "I'm leaving, goodbye", 
                 "See you soon, take care", "Take care, see you"],
    "Contact information": ["How can I contact you?", "What's the phone number?", "Do you have a WhatsApp number?", 
                            "What's your email address?", "How do I communicate with support?", "Do you have phone support?", 
                            "Where can I locate you?", "Can I contact you by chat?", "Do you have a contact form?", 
                            "Where can I find contact information?", "Can I call you for support?", "Do you have a direct line?"],
    "Business hours": ["What are the business hours?", "What days are you open?", "What time do you open?", 
                       "What are the customer service hours?", "Do you have special hours?", 
                       "Can I visit the store on weekends?", "Are you open on Sundays?", "What are the opening hours?", 
                       "Until what time are you open?", "What days do you attend?", "Are the hours the same every day?", 
                       "Can I make a call outside regular hours?"],
    "Prices": ["How much does the product cost?", "What's the service price?", "How much does this product cost?", 
               "Could you tell me the service price?", "Are there available discounts?", "Is this the final price or are there additional taxes?", 
               "I need to know the costs before deciding.", "Does the price include shipping?", "Do you have business prices?", 
               "Do you offer payment plans?", "Is this price valid for all products?", "Does the price change according to quantity?"],
    "Return policy": ["What's the return policy?", "Can I return the product?", "Until when can I return it?", 
                      "What are the requirements for a return?", "Do I have to pay for return shipping?", 
                      "Can I exchange a product?", "How do I process a return?", "Can I return it if it's used?", 
                      "How long does the refund take?", "What should I do if the product arrives defective?", "Can I return it at the store?"],
    "Technical support": ["I have a technical problem", "How can I solve an error?", "I have a problem with the product, can you help me?", 
                          "How do I resolve a system error?", "I don't know how to install it, can you give me technical support?", "The device won't turn on, what can I do?", 
                          "There's a recurring failure in my application, I need help.", "The system crashes, how do I fix it?", "Can you help me with the configuration?", 
                          "My device doesn't work, what should I do?", "I can't access my account, can you help me?", "How do I restore the system?"]
}