version: '3.8'

services:
  flask-app:
    build: .
    container_name: chatbotflaskapp
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    stdin_open: true
