



diccionario = {
    "Saludo": ["Hola", "Buenos días", "Buenas tardes", "¿Cómo estás?", "Hola, ¿cómo están?", 
               "Muy buenos días, ¿pueden ayudarme?", "Buenas tardes, necesito información.", 
               "Hola, ¿hay alguien disponible?", "¡Saludos!", "¿Qué tal?", "¡Qué tal todo!", 
               "¡Hola, espero que estén bien!", "¡Buenos días! ¿Qué tal todo?", "¡Buenas tardes! ¿Cómo puedo ayudarte?", 
               "Hola, ¿qué tal todo por ahí?"],
    "Queja": ["Quisiera hacer una queja", "No estoy satisfecho con el servicio", "El producto llegó dañado", 
              "No me ha gustado la atención recibida", "El servicio fue muy lento", "La calidad del producto no es buena",
              "Estoy insatisfecho con lo que recibí", "El envío fue demorado", "No estoy contento con la compra", 
              "El producto no cumplió con mis expectativas", "El servicio no fue como esperaba", "Me siento decepcionado con la compra"],
    "Reclamo": ["Necesito reclamar por un error", "Quiero hacer un reclamo", "Esto es inaceptable, quiero una solución",
                "Estoy muy molesto, necesito hacer un reclamo.", "Quiero reportar un error con mi pedido.",
                "Esto no cumple con lo que prometieron, quiero una solución.", "El producto no funciona, ¿cómo hago un reclamo?",
                "Quiero mi dinero de vuelta, el producto llegó en mal estado.", "Esto es un error grave, necesito ayuda.",
                "No me han respondido a tiempo, quiero hacer un reclamo", "Este problema es urgente, necesito que lo resuelvan ya", 
                "Mi producto no funciona, quiero saber qué hacer"],
    "Petición": ["Me gustaría pedir información", "Necesito saber más detalles sobre el producto", "Por favor, envíenme más información", 
                 "¿Pueden darme más detalles?", "Quisiera saber más sobre sus servicios", "Por favor, envíenme una cotización", 
                 "Me gustaría conocer las características del producto", "¿Podrían enviarme más información por correo?", 
                 "Estoy interesado en saber más", "¿Tienen algún catálogo de productos?", "¿Me pueden dar detalles adicionales?", 
                 "¿Cómo puedo obtener más información sobre lo que ofrecen?"],
    "Despedida": ["Adiós", "Hasta luego", "Nos vemos", "chao", "hasta pronto", "gracias", "Cuídate", "Hasta la próxima", 
                  "Que tengas un buen día", "Nos vemos pronto", "Hasta entonces", "Gracias por todo", "Me voy, adiós", 
                  "Hasta pronto, que estés bien", "Cuidate, nos vemos"],
    "Información de contacto": ["¿Cómo puedo contactarlos?", "¿Cuál es el número de teléfono?", "¿Tienen un número de WhatsApp?", 
                               "¿Cuál es su correo electrónico?", "¿Cómo me comunico con el soporte?", "¿Tienen atención telefónica?", 
                               "¿Dónde los puedo ubicar?", "¿Puedo contactarlos por chat?", "¿Tienen un formulario de contacto?", 
                               "¿Dónde puedo encontrar información de contacto?", "¿Puedo llamarlos para soporte?", "¿Tienen línea directa?"],
    "Horario de atención": ["¿Cuál es el horario de atención?", "¿En qué días están abiertos?", "¿A qué hora abren?", 
                            "¿Cuáles son los horarios para atención al cliente?", "¿Tienen horarios especiales?", 
                            "¿Puedo visitar la tienda en fin de semana?", "¿Abren los domingos?", "¿Cuál es el horario de apertura?", 
                            "¿Hasta qué hora están abiertos?", "¿Qué días atienden?", "¿El horario es el mismo todos los días?", 
                            "¿Puedo hacer una llamada fuera del horario habitual?"],
    "Precios": ["¿Cuánto cuesta el producto?", "¿Cuál es el precio de servicio?", "¿Cuánto cuesta este producto?", 
                "¿Podrían decirme el precio del servicio?", "¿Hay descuentos disponibles?", "¿Es este el precio final o tiene impuestos adicionales?", 
                "Necesito saber los costos antes de decidirme.", "¿El precio incluye envío?", "¿Tienen precios para empresas?", 
                "¿Ofrecen planes de pago?", "¿Este precio es válido para todos los productos?", "¿El precio cambia según la cantidad?"],
    "Política de devolución": ["¿Cuál es la política de devoluciones?", "¿Puedo devolver el producto?", "¿Hasta cuándo puedo devolverlo?", 
                               "¿Cuáles son los requisitos para una devolución?", "¿Tengo que pagar por el envío de la devolución?", 
                               "¿Puedo cambiar un producto?", "¿Cómo proceso una devolución?", "¿Puedo devolverlo si está usado?", 
                               "¿Cuánto tiempo tarda el reembolso?", "¿Qué debo hacer si el producto llega defectuoso?", "¿Puedo devolverlo en la tienda?"],
    "Soporte técnico": ["Tengo un problema técnico", "¿Cómo puedo solucionar un error?", "Tengo un problema con el producto, ¿pueden ayudarme?", 
                        "¿Cómo resuelvo un error en el sistema?", "No sé cómo instalarlo, ¿me pueden dar soporte técnico?", "El dispositivo no enciende, ¿qué puedo hacer?", 
                        "Hay un fallo recurrente en mi aplicación, necesito ayuda.", "El sistema se cae, ¿cómo lo soluciono?", "¿Me pueden ayudar con la configuración?", 
                        "Mi dispositivo no funciona, ¿qué debo hacer?", "No puedo acceder a mi cuenta, ¿pueden ayudarme?", "¿Cómo restauro el sistema?"]
}